global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8080']

  - job_name: 'datacollector'
    metrics_path: /metrics
    static_configs:
      - targets: ['datacollector:80']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']